### ISSUE TITLE
Behat failing on moodle 4.0 / current master

### ISSUE THREAD

**Issue by PhMemmel** [moodlehq/moodle-docker#207]
I've tried to run behat test with a clean moodle repository with master branch

I set `MOODLE_DOCKER_WWWROOT` to the moodle repo and `MOODLE_DOCKER_DB` to `mariadb`.

Running behatinit is working perfectly. However, running `bin/moodle-docker-compose exec -u www-data webserver php admin/tool/behat/cli/run.php --tags=@block_search_forums` (just an example tag) leads to:

```
Running single behat site:
Behat requirement not satisfied: http://webserver is not available, ensure you specified correct url and that the server is set up and started.
 More info in https://docs.moodle.org/dev/Running_acceptance_test

To re-run failed processes, you can use following command:
php admin/tool/behat/cli/run.php --tags="@block_search_forums" --rerun
```

This seems to be related to moodle 4.0. Switching to `MOODLE_311_STABLE`, rerunning behat init and executing the command above everything works without a problem.

**Comment by stronk7** [comment]
Uhm, @PhMemmel ,

have you you got it working? Sorry for the late reply but I cannot find anything causing that problem and both [CI](https://github.com/moodlehq/moodle-docker/actions/runs/3157861505/jobs/5139237356) and local runs say this is working with 400 and 4.1dev (master) perfectly.

If there is any other detail able to make us reproduce the problem, great, but right now it seems that everything is working ok, so far.

Ciao :-)

**Comment by PhMemmel** [comment]
Hi @stronk7, thank you picking up on this. I managed to get it back to work and simply forgot to close this issue, sorry for that. Unfortunately, too much time has passed since then so I do not really remember how I fixed it, but it was nothing related to the docker repo. Again thx and sry, Issue closed.

**Comment by mackensen** [comment]
I'm seeing this on current `master` with a custom-compiled PHP 8.2 container from #248. Continuing to troubleshoot.

**Comment by scara** [comment]
Hi @mackensen,
could https://github.com/moodlehq/moodle-php-apache/issues/174 be of any help?

Shortly a recent change in the PHP base image requires the user to be specified when creating soft links in the container: `-u www-data`.

HTH,
Matteo

**Comment by stronk7** [comment]
Also, note that Moodle still doesn't support php82, it's WIP @ https://tracker.moodle.org/browse/MDL-76405
